name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint_test:
    name: "Test"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: |
        echo @"
        {
          "version": "2.1.0",
          "`$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.4",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "Pylint"
                }
              },
              "results": [
                {
                  "ruleId": "no-unused-vars",
                  "level": "error",
                  "message": {
                    "text": "'x' is assigned a value but never used2."
                  },
                  "locations": [
                    {
                      "physicalLocation": {
                        "artifactLocation": {
                          "uri": "file:///D:/a/bugaled/bugaled/.github/workflows/lint.yml"
                        },
                        "region": {
                          "startLine": 8,
                          "startColumn": 1
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
        "@ > test.sarif
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: test.sarif
